### ISSUE TITLE
Version 1.5 unable to preview on JLCPCB & PCBWay

### ISSUE THREAD

**Issue by EthanChinCN** [MrHDR/MBC3-Flashcart#2]
1. Uploaded to JLCPCB or PCBWay. The preview section won't render any images
2. JCLPCB won't automatically detect dimensions, require manually input
3. JCLPCB online Gerber viewer won't render, prompt error "Unable to identify the layers due to the non-standard filename"
<img width="358" alt="CleanShot 2022-02-21 at 11 22 44@2x" src="https://user-images.githubusercontent.com/28820099/154883968-d40dbb7c-4bfe-42bd-89dc-df9933ff1919.png">

**Comment by HDR** [comment]
Whoops forgot to close this, fixed with d55d2eb1419be985161d65bb1fd4a22e397ddbc2

**Comment by scr-trees** [comment]
The preview is rendered on JLCPCB, but the same errors are given: "unable to identify layers", "cannot identify board outline", and several "non-gerber274x/excellon formats". Is it still ok to order?

edit: I think I see now. Maybe the .zip file from the "releases" section has not been updated to the working version?

edit2: "B_Paste.gbp" is still showing as non-gerber/excellon format. Any issue there? 

[
![A55CB2B9-AE8B-4966-9325-C2D44D1A304E](https://user-images.githubusercontent.com/47956462/193473350-e85db35e-acae-410c-abbb-52f35a494d00.png)
](url)

**Comment by HDR** [comment]
This is a JLC gerber rendering issue, previews on pcb manufacturing sites are often broken or just wrong.

**Comment by scr-trees** [comment]
So it's fine without B_Paste.gbp?

**Comment by HDR** [comment]
yes, it's just a rendering issue
